### ISSUE TITLE
Cython not installed. at every appears every time I turn on vscode

### ISSUE THREAD

**Issue by Eveheeero** [ktnrg45/vs-code-cython#1]
In wsl ubuntu 20.04, I'v installed python3 (3.8.10 ubuntu default) and python3.9 (3.9.5)

Every I turn on vscode, Cython not installed pop up appears. 

If I click install button, then /bin/python3.9 -m pip install cython command launched.

But I already had installed cython on both python.

I use python3.9(3.9.5) in vscode

**Comment by ktnrg45** [comment]
Thanks for reporting this. This should be fixed in v0.0.10.

**Comment by Eveheeero** [comment]
That bug doesn't happen in new version, thank you.
