### ISSUE TITLE
Problems with asterisk in 'sizeof', multiple slices in view and 'with nogil' 

### ISSUE THREAD

**Issue by vathomass** [ktnrg45/vs-code-cython#16]
Hi,

Once more, thanks for the useful extension. I am facing some issues with asterisks, and when using the keyword `parallel`.
First, I get an "Expected expression" when try to raise exceptions in `cdef` function that return `void` as
```
 cdef void func(int iprb, double [:, ::1] pout, int ifld) except *:
    if iprb > 12:
        raise ValueError('This it too high')
    do staff
``` 

Second, I get a ""(" was not closed" when try to allocate memory to hold pointer to doubles, aka (`double *`),
```
pointer_array = <double **> malloc(sizeof(double *) * 45)
```

Finally I get "Expected :" just before the `parallel` keyword, in the following example
```
 with nogil, parallel(num_threads=nthreads):
    allocate some per thread staff here
    for ik in prange(num_compute, schedule='static'):
        do staff
```

Note that the snippets above compile without any problem in cython.
Hope the report is not too long.

Best Regards,
Thomas

**Comment by ktnrg45** [comment]
All of the issues should be fixed in version 0.3.8

**Comment by ktnrg45** [comment]
Actually I noticed a pretty bad regression/side effect for the sizeof parsing so that issue is still unresolved.

**Comment by ktnrg45** [comment]
Should be fixed now
