### ISSUE TITLE
Syntax highlighting is not working

### ISSUE THREAD

**Issue by fsteinmetz** [ktnrg45/vs-code-cython#5]
Thanks a lot for this extension !!!
Syntax highlighting is not working for me though (everything is white) ; the rest seems to be working. I am using v0.1.2

**Comment by ktnrg45** [comment]
Do you have any other Cython extensions installed? They may be overriding this extension's syntax highlighter.

**Comment by fsteinmetz** [comment]
Oops... I thought I had removed them, but actually not. Sorry for the noise.
Having cython support in vscode is such a relief, many thanks again !!
