### ISSUE TITLE
C++ Syntax Support

### ISSUE THREAD

**Issue by fancyplants** [ktnrg45/vs-code-cython#6]
Loving this extension as I learn and try to develop Cython. I would really love to have C++ syntax support as well, and I also want to contribute to that process (as well as any other help I can provide to developing this language server further!). How can I contribute?

**Comment by ktnrg45** [comment]
Hi. Thanks I appreciate any help I can get. Right now, the main roadblock is parsing the CPP syntax while not affecting the parsing of the C syntax and the original Python syntax. If you would like to take a crack at it, I have a cpp branch in the [cyright repo](https://github.com/ktnrg45/cyright) started. You can fork that repo and then submit a pull request there.

**Comment by fancyplants** [comment]
How do I get started? I have developed in TS/JS and Python for a while already, but I don't quite understand how to run the project. Do you have an example of how you'd test a file's syntax? (So I can make a Cython file with CPP syntax and continually iterate against it)

**Comment by ktnrg45** [comment]
There are some instructions in the readme for setting up a dev environment.

First I would fork the cyright repo and then clone this repo and set the remote of the cyright submodule to your fork.
Then install node dependencies by running:
`npm install --include=dev`

Once that is done you can run the 'Watch Extension'  VS Code task which will automatically build the language server when changes are made.

Once it is built you can run the extension using the "Extension" launch target.

By the way, basic cpp support has been added, but will probably need some improvements.
Feel free to submit any improvements if you have any.
