### ISSUE TITLE
Extension reporting errors with valid syntax

### ISSUE THREAD

**Issue by ahsand97** [ktnrg45/vs-code-cython#7]
Hello there!

First of all thank u, this extension is really nice and basically the only one who works out of the box for me using Code - OSS under Linux.

I've been working in a project that includes cython to wrap some C libraries and I've noticed that this extension report some issues with valid syntax, or at least I think it's valid (it compiles and based on documentation), so I have to use `# type: ignore` to avoid the issues but as long as the project grows I just have to keep adding that comment more and more.

**First issue:**
Exposing functions from external libraries are reported as issues

Based on [official documentation](https://cython.readthedocs.io/en/latest/src/tutorial/clibraries.html#defining-external-declarations), this is how to expose functions from external library:

```cython
cdef extern from "<X11/Xlib.h>":
   # typedefs ...

   # functions
   int XQueryTree(  # <--- Error reported unless # type: ignore is used
        Display *display,
        Window window,
        Window *root_return,
        Window *parent_return,
        Window **children_return,
        unsigned int *nchildren_return
    )
```

![image](https://user-images.githubusercontent.com/32344641/207439282-226279b6-ce82-4305-988b-22edc1828e92.png)
It happens with all exposed functions.

**Second issue:**
Casting to a function typedef is reported as an issue.
Based on [official documentation](https://cython.readthedocs.io/en/latest/src/tutorial/clibraries.html#defining-external-declarations) you can use `<desired_type> the_variable` to type cast. When casting to a function typedef I see an issue

```cython
cdef extern from "<X11/Xlib.h>":
    # typedefs
    ctypedef int (*XErrorHandler)(Display *display, XErrorEvent *error_event)

    # functions
    XErrorHandler XSetErrorHandler(XErrorHandler *handler)  # type: ignore

cdef int default_x_error_handler(Display *display, XErrorEvent *error_event):
    print('hello world')
    return 0

cdef set_error_handler():
    cdef XErrorHandler *xerrorhandler = <XErrorHandler*>&default_x_error_handler # <-- Error reported unless # type: ignore is used
    XSetErrorHandler(handler=xerrorhandler)
```

![image](https://user-images.githubusercontent.com/32344641/207442727-d9e12b23-a85d-45e7-bf38-34abe6bf74de.png)

**Third issue:**
Initializing struct directly reported as an issue. This is NOT in the official documentation but is [supported](https://stackoverflow.com/questions/52380841/how-do-i-set-all-the-values-of-a-struct-in-one-go). Basically, you can initialize a struct with:

```cython
ctypedef struct myStruct:
    int a, b, c

cdef myStruct myVar = [1, 1, 3] # <-- Values are passed directly as if it was a list
cdef myStruct myOtherVar = myStruct(a=1, b=2, c=3) # <-- Values are passed as if the struct had a constructor
```
Both ways it end up in error:
![image](https://user-images.githubusercontent.com/32344641/207444854-861ed288-5e67-4106-a621-abfbd5b5578d.png)

![image](https://user-images.githubusercontent.com/32344641/207444947-de14f4f0-73ef-4724-9eca-d195ba4868d2.png)

Those are the issued I've noticed so far.

**Update**: for the last issue I've found this portion in the [official documentation](https://cython.readthedocs.io/en/latest/src/userguide/language_basics.html#structs-unions-enums) where a struct is initialized using the constructor:

```cython
cdef struct Grail:
    int age
    float volume

def main():
    cdef Grail grail = Grail(5, 3.0) # <-- struct initialized directly using non keyword constructor
    print(grail.age, grail.volume)
```

**Comment by ktnrg45** [comment]
Hi,

The extension should no longer report these errors. See #10
