### ISSUE TITLE
"Excepted expression" when `prange` is used with the `nogil` optional argument 

### ISSUE THREAD

**Issue by vathomass** [ktnrg45/vs-code-cython#8]
Hi,

Thanks for the nice extension, it is very useful.
The extension reports a problem when I use the `prange` loop with the `nogil` parameters as:
```
for ik in prange(num_tot, nogil=True, schedule='static', num_threads=nthreads, chunksize=chunk_size):
    do staff
```
I assume is gets confused with the `nogil` keyword of cython.

Best Regards,
Thomas

**Comment by ktnrg45** [comment]
Thanks for the report. `nogil` and  `gil` are now soft keywords.
